### ISSUE TITLE
Introduce yourself...

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall22#1]
Hi everyone -

I thought I'd kick off a post where everyone can reply with an introduction to themselves so we can get to know each other.

**Tell us what brought you to this course and any other details you care to share.**

A little bit about myself - I'm a web programmer and educator, living in Orange, MA. 

In addition to this course, I also teach [CSCI E-15](https://hesweb.dev/e15). In the past, I've taught at Wellesley, UPenn, and UMiami. When working in industry I was the head developer for an online e-commerce store. Independently, I do private consulting and share free web development guides and videos via https://codewithsusan.com.

More about my background here: [susanbuck.net](https://susanbuck.net/)

All in all, I love creating things with code and teaching others how to do the same.

Looking forward to getting to know you all!

**Comment by JenniWhitman** [comment]
Hey there! 
I'm Jenni and I'll be helping out as a teaching assistant this semester. I've TA'd for Susan in the past, for E-15, and I'm stoked to be back this semester.  I'm always willing to field questions and help find good solutions. One thing I have learned over the years is that 9 times out of 10 the best answer is the one we research and figure out together rather than an off the cuff response.

Outside of being a TA, I'm a full-stack engineer for a startup working mainly in Python & React these days, but I have worked all over a few stacks in everything from PHP to Java to Angular and beyond.  I've worked from small startup all the way up to big megacorporation and a few places in-between as well.

Outside of class I have a couple kiddos, play a lot of games, and sometimes even climb mountains. I'm located in Maryland for now, but am often in the Boston area.

Excited for the semester and can't wait to meet you all!

**Comment by RobertHolzhauser** [comment]
Hello Everyone!

Robert Holzhauser here, and I'm really looking forward to our class this semester.   I work as a developer at a telecom and haven't done much with PHP, though I've dabbled a little bit over the years.   I volunteer as a web-master for a Scout troop which has a site with a lot of PHP, so I figured I should get up to speed.

I live with my amazing family (wife, son, daughter, small parrot, turtle, and hermit crabs) in Parker, Colorado, which is about 30 miles South East of Denver.   Lately I've been spending a fair bit of time helping my son ramp up his baseball skills so he can make his high school team this spring.  I also enjoy working out a few times each week, and try to find time semi-regularly to be outdoors in some form or another.

Enthusiastically,
Robert

**Comment by bar181** [comment]
Hi all !
I'm Bradley.  This is my 4th class on my way towards an ALM in Digital Media. I'm a course assistant for CS50. I'm quite familiar with PHP and Vue but only in aspects I use every day.  Looking forward to learning the proper way of doing things. 

Outside class, I try to paint and have fun with my fam here in Toronto Canada.
  
Here's my linkedin if anyone wants to connect https://www.linkedin.com/in/bradaross/

Excited to meet everyone

**Comment by shawnnasseri** [comment]
Hello, 
I am Shawn.  This is my 9th class and working toward my 3rd Grad cert.  Really enjoying the classes.

**Comment by traveler9878** [comment]
Hi David Curtis.  Mostly living in Maryland, spending some time down in South Carolina on a regular basis.  Looking forward to this PHP course.  Taking this course to get some hands on with PHP and hoping to finish up the ALM in the spring.

**Comment by RobbieRhodes94** [comment]
Hello everyone my name is Robbie Rhodes and this is my first class with the Harvard Extension school. I currently work at the Harvard Divinity School full time in IT & Media Services and I am hoping to get my graduate degree in the Digital Media Design program. I have some experience in writing HTML with Adobe Dreamweaver but still would consider myself rather new to web programming. I am eager to learn more and am looking forward to the class.

**Comment by kristinjohnson1** [comment]
Hello everyone! 

My name is Kristin Johnson and this is my third class with Harvard Extension School working towards a graduate certificate in Web Technologies. I currently work for HUIT on the Service Desk. I have a bachelor's degree in Computer Science from Wentworth Institute of Technology in Boston so I do have some experience with PHP but am in need of a refresher. 

Outside of class and work, I enjoy baking and spending time with my dog.

**Comment by bob62683** [comment]
Hi All! My name is Robert Vernam and this is my 4th class in pursuit of my ALM in Information Management Systems. I'm currently a Network Engineer at PwC, but have a little background in PHP programming from years back. Looking forward to knocking dust off that skillset.

I currently live in Plymouth, MA and really sad to see beach season coming to a close!

**Comment by berhanwa** [comment]
Hey everyone!

I'm Bethlehem Berhanu, a Dallas-based Web Designer at Signet Jewelers. My background is in the arts and graphic design so I'm still quite new to programming. I have taken some courses on front-end code and PHP which were enjoyable and I am excited about this course!

This is my first semester at HES, and I plan to graduate with my ALM in Digital Media Design. 

Some things about me - I enjoy cooking healthy meals, watercolour painting and working on puzzles. My husband and I live in the city with our 1 year old orange tabby who's quite the character! I also enjoy learning languages and am currently working on my French via Duolingo.

Looking forward to a great semester learning with you all!

**Comment by anc6314** [comment]
Hello!

I am Anthony Coleman and I work in Public Relations at Alabama Power / Southern Company.   I am working on a ALM degree in Information Management Systems.   I am located in Birmingham, Alabama.

In my free time, I do pro bono legal work as I already have a law degree and have been admitted to the bar.

Looking forward to jumping into PHP with all of you!

**Comment by micoso** [comment]
Hello all
I am Michelle Soso and I'm completing my masters in Digital Media Design to fulfill degree requirements for permanent teaching certificates (Technology Specialist and Attendance Teacher/Truant Officer) at NYCDOE where I currently work.  

I have spent nearly equal portions of my life in: NYC (born); Canada (Toronto/Ottawa/Montreal school yrs) and the island nation of St. Vincent and the Grenadines (post-grad contracts 1995-2004)  I live with my son (Game Dev.), an orange Tabby and a grey short-hair tuxedo (both rescued as kittens and still act like they are 7 and 6 months not 17 and 16 years)

Discovered in 1999 that I was considered a "Technology Unicorn" when I lead the team that developed the first projects of e-government in St. Vincent and the Grenadines. The Cabinet and Budget Committee thought I was crazy to want to spend $5M on "a website" www.gov.vc .  I enjoyed working on the creative design of templates for the front-end sites; tackling the problems of back-end server and security issues (solved some by running a few miles of fiber optics) and drafting internet use laws, policy and regulations.   I learned HTML, CSS, Java and Maya when they were first released and paid an arm and a leg for the first Adobe Suite for Windows 98. My skills are rusty from many years away from the hard-core design and programming (busy Mommying)   Trying to get back into Tech for a career change opportunity when I retire by collecting all 4 grad certificates as I complete the masters degree at HES.

**Comment by duyvhh** [comment]
Hi all

I am Van and I am a graduate student at HES, track: Information Management System. I currently work for in Telecommunication industry and have bachelor degree in Information System. My primary languages are Java and Go, and through this course, I hope to learn more about PHP.

I enjoy reading and swimming when I have free time.

Looking forward to learning from you all

**Comment by q8** [comment]
Hey all,

I am Homoud. I am from Kuwait and I'm a master's degree candidate at Harvard Extension School. Excited to be here and looking forward to learning more about web development in this semester.

**Comment by richiecarey** [comment]
Good morning all,

I'm Richie Carey, a (primarily) front end developer from Cape Cod, Massachusetts. 

Although I do have exposure to PHP through my day job working with the Drupal 9 content management system, I'm aware my skills are rusty and limited. I'm excited to have the opportunity to re-learn modern PHP from the ground up, beginning this semester and continuing on through CSCI E-15 and Laravel next semester.

Happy to be here, looking forward to learning with you all!

Thanks,
Richie

**Comment by andlearnmore** [comment]
Hi! I'm Anne, and this is my second course toward a Programming graduate certificate. In addition to studying at HES, I also work here directing our certificate programs. (Really happy to see other certificate earners here!)

I love swimming, hiking, board games (can't get enough Wingspan), and am working on brushing up on my German.

I'm really looking forward to being in class with all of you and learning together!

**Comment by kgondim** [comment]
## Hi everyone!
My name is Kristen Gondim. I'm still pretty new to web development and programming, but this is my 4<sup>th</sup> class in this domain. I chose this class to fulfill requirements for both a digital media certificate and digital media minor for an undergraduate degree. This will be my **final** semester at Harvard Extension, and this class is one of the two remaining classes I need to complete my undergrad program *yay!* 
I'm ready to get into it with all of you!

**Comment by kevinzomg** [comment]
Hello all, 

My name is Kevin Zong and I am a ballet dancer with Singapore Ballet. I moved to Singapore from America last November, and I've been doing my university remotely via HES for the past several years. I'm roughly 3/4 of the way through my ALB, and I've recently taken an interest in web programming and the like. My experience in web programming is relatively slim, having only taken a few courses from HES, but I've been actively maintaining a website for my mother's small business. I'm hoping to deepen my IT knowledge, and perhaps open new pathways to income, as dancing is a relatively short and finite career. 

Aside from work and school, my main hobbies include mechanical keyboards (building/collecting), and photography. If there would happen to be any other mechanical keyboard enthusiasts here, I'd love to connect!

Here's to a productive semester~!

**Comment by JacquiLJQ** [comment]
Hi guys, 

My name is Jiaqing Li, and you can just call me Jacqui. I am an entrepreneur and CEO of a blockchain startup company. I enjoy entrepreneurship and am currently pursuing an ALB degree at HES.  This is the 3rd class that I took in the CS field. Please feel free to send me msg if you want to talk about blockchain, web3, or anything else!
