### ISSUE TITLE
Lecture's code

### ISSUE THREAD

**Issue by ghost** [susanBuck/e2-fall22#11]
Hi,

I'm trying to find the code from the lecture but I can't. Is it in "Code > Commits"?

**Comment by andlearnmore** [comment]
I found them here: https://github.com/susanBuck/e2

**Comment by micoso** [comment]
I'm missing something and I can't figure it out.  I have gone over the setup for subdomains several times.

http://e2practice.hesgradwork.me/  This works and you can see the page I have there.

http://e2practice.hesgradwork.me/bank.php  My piggy bank page works.

http://e2p1.hesgradwork.me/  My p1 page only shows the blue LEMP page.
I don't know where the error occurs or where it is....

**Comment by susanBuck** [comment]
@micoso - Can you create a new thread with this issue? Each separate issue should have its own thread.

Also, in that thread can you include the contents of your subdomain config file located at `/etc/nginx/sites-available/hes`?

Also, please include the output of running the command `nginx -t` on your server. As noted in the [Subdomain](https://hesweb.dev/e2/notes/infrastructure/subdomains) notes, this command will tell you if their are any errors in your configuration file.

**Comment by susanBuck** [comment]
To reply to @2015cambridge's question -

@andlearnmore Is correct. The URL for my e2 repository is https://github.com/susanBuck/e2. 

Just for reference, at the end of of the [Week 4 outline](https://hesweb.dev/e2/week/4
) is a link to the [/e2/practice/week4.php](https://github.com/susanBuck/e2/blob/main/practice/week4.php) file within this repository that contains all the code from Week 4.

If there's anything else within this repository you're trying to locate and are unable to, just let us know!

**Comment by ghost** [comment]
Thank you very much
