### ISSUE TITLE
Image as variable

### ISSUE THREAD

**Issue by ghost** [susanBuck/e2-fall22#15]
Hi everyone,

Is it possible for me to save a picture in a variable and include it in the output?

Thank you.

**Comment by susanBuck** [comment]
Technically yes, image data can be saved as its encoded text form in a variable. But that's not the approach I would go with handling/displaying images.

Instead what you should store in the variable is a **path to an image**. 

For example, imagine you had this PHP:

```php
$imagePath = '/images/example.png';
```

Then in the view you could do this:
```html
<img src='<?php echo $imagePath?>'>
```

And of course this then opens you up to programmatically decide on images. Here's a hypothetical: 
```php
if($correct) {
    $imagePath = '/images/happy-face.png';
} else {
    $imagePath = '/images/sad-face.png';
}
```

**Comment by ghost** [comment]
Thank you very much. It helps a lot.
