### ISSUE TITLE
Call variable from within variable

### ISSUE THREAD

**Issue by ghost** [susanBuck/e2-fall22#16]
Hi,

If I store a variable inside another variable in index file, how do I call it from view file, I'm trying the following:

view file:
```php
$imagePath = '/images/example.png';`
```

```php
if(statment){
$result="$imagePath"}`
```

index file:
```html
<img src='<?php echo $result>'>
```

Thank you

**Comment by susanBuck** [comment]
This line is missing a closing PHP tag:
```php
<img src='<?php echo $result>'>
```

It should be:
```php
<img src='<?php echo $result ?>'>
```

If that doesn't resolve your issue, let me know more about how it's failing. For example, is the image just not loading or are you getting an error message? If the latter, what is the error message?

Also, it's always helpful to include links to the relevant files in your Github repository so we can see exactly what you're working with.

**Comment by susanBuck** [comment]
One more thing: when setting the _$result_ to _$imagePath_, do not put _$imagePath_ in quotes. 

It should look like this:

```php
if(statement) {
    $result = $imagePath;
}
```

**Comment by ghost** [comment]
thank you

**Comment by traveler9878** [comment]
This is a good question.  The things you may want to start thinking about in this case are the scope of the variable and if it is called/passed/assigned by value or by reference.  If this question gets you to the point where you understand the questions above that's a big win at this point.  They're starting to introduce these concepts gradually now and I'm sure we'll have a handle on them in full before the course is over.

**Comment by ghost** [comment]
Thank you, I'm excited to learn more about it from course's materials
