### ISSUE TITLE
Extra TA hours tonight

### ISSUE THREAD

**Issue by JenniWhitman** [susanBuck/e2-fall22#17]
Hey folks - since there were technical issues last week and p1 is looming, I'll open the Zoom tonight at 6PM for anyone who wants to pop by, and keep it open till about 8 (EST).

Thanks!
[Zoom link](https://us04web.zoom.us/j/3793987206?pwd=BCGvtMMLo1ILidXCM7LFM6bG0VojaJ.1) 

passcode (if it doesn't go straight in): jVQPN5

**Comment by micoso** [comment]
WOOO WHOO!!!!  My prayers are answered.  
I was wishing it as I fell further down the php rabbit hole and took a break. :) 
See you around 6:30.
