### ISSUE TITLE
form-a code 

### ISSUE THREAD

**Issue by ghost** [susanBuck/e2-fall22#19]
I copied "form-a" code and use it to test a random word . Everything look fine but when I click "check answer," I get a blank page.
Does anyone experience the same?

**Comment by susanBuck** [comment]
Can you update your Github repository with your latest code so we can see your code exactly as you're seeing it? Also, please share the URL to where we can replicate the problem.

**Comment by ghost** [comment]
Thank you for replying,

I don't know why, but it is working now.

Thank you again

**Comment by susanBuck** [comment]
Ok, glad it's sorted out. I'll close this thread but feel free to re-open or start a new thread if you face additional issues.
