### ISSUE TITLE
Associative array

### ISSUE THREAD

**Issue by ghost** [susanBuck/e2-fall22#21]
Hi,

How to access the first key or value of an associative array?

Thank you

**Comment by susanBuck** [comment]
PHP's [array_key_first](https://www.php.net/manual/en/function.array-key-first.php) function can give you the first key of an array.

Once you know this, you could access the first value. Example:

```php
$example = [
    'first_name' => 'Jill',
    'last_name' => 'Smith',
    'age' => 25
];

$firstKey = array_key_first($example);
$firstValue = $example[$firstKey];
```

**Comment by ghost** [comment]
thank you very much

**Comment by ghost** [comment]
Sorry to ask again,
Is it possible to choose any key or value from an associative array? for example   first, second, and thirds, as we would with a standard array. 

I did find a way to select the last one. but not the others in the middle.

**Comment by micoso** [comment]
2015cambridge, perhaps it would be like finding the 'nth child' in html and css?
I don't recall the terms to explain it, but if you were trying to create something like a list of links for a navigation bar and the font was blue but you wanted the second to last one red there was coding about finding the first, the last and an "nth child of the array".  If you made changes to the actual link text or even reposition things, as long as you still wanted the second to last one red, you wouldn't need to recode the whole page because the program would find that nth child for you and make it red.

**Comment by richiecarey** [comment]
Hi @2015cambridge .. I don't believe there is a way to access an associative array by integer index but you may want to have a look at the `array_keys` function ..

[https://www.php.net/manual/en/function.array-keys.php](https://www.php.net/manual/en/function.array-keys.php)

.. you could use that function to return an array of keys for the `$example` array. Then, use that array to find the key for the integer index you want to access.

For example ..

`$keys = array_keys($example);`

`echo $example[$keys[0]];`

.. would print `Jill`.

Hope this helps!

**Comment by ghost** [comment]
> 

Thank you so much

**Comment by RobertHolzhauser** [comment]
Not sure if this will help or not.
Are you looking for a specific value in the array, or do you want x position?  If you want a specific value from an associative array that you have the key for, of course the basic way to access would be something like:

`
$array = array(
    "foo" => "bar",
   "goo" => "car",
   "hoo" => "dar",
   "ioo" => "iar"
) 
$my_value = $my_array['goo'];  

echo $my_value;    #expect to see car
`
So, if you have an associative array, and know the key you are looking for, the position in the array doesn't matter, just provide the key.

On the other hand, if it's more important to be able access based on position in the array, you can access any position directly by putting the position you want to check in brackets.  For example, if I have an array of fruit, and I want to access the 3rd fruit in the array I could do something like the following:

`
$fruit = array("orange", "banana", "apple", "raisin");
$my_fruit = $fruit[2];
echo $my_fruit;   # expect to see apple
`

So, if you have the key you don't need the position.  If the position is important, perhaps you don't need an associative array, but just a basic array.

All the best,
Robert

**Comment by traveler9878** [comment]
Pretty sure if you 'reset' the array it will make the first element the current element and using 'key' will return the first key.  Seems to be a use of 'current' to get the corresponding current value.

**Comment by ghost** [comment]
thank you
