### ISSUE TITLE
Project 1 grading update

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall22#22]
**UPDATE: Grades have now been posted. You can view your points/feedback information in Canvas.**

**Thanks again everyone for your patience!** 

---

Hi all,

Project 1 grades/feedback - part of the Week 7 Assignment - were due to be released today (Wed) by midnight, but I'm running a day behind due to travels/a family emergency. Because of this, I will release grades/feedback tomorrow (Thu) by midnight.

As a thank you for your patience I will be giving each student "1 free late pass" and deducting the late penalty of one regular week assignment (e.g. not a project week assignment). I will apply this at the end of the semester.

Thanks in advance for your understanding! 

-Susan

---

**Comment by andlearnmore** [comment]
I am sorry to hear you've had a family emergency. I hope everyone and everything is ok!
-Anne

**Comment by traveler9878** [comment]
Same

**Comment by JacquiLJQ** [comment]
Sorry to hear that. Hope everything is fine!

**Comment by richiecarey** [comment]
hope all is well!

**Comment by susanBuck** [comment]
UPDATE: Grades have now been posted. You can view your points/feedback information in Canvas.

Thanks again everyone for your patience!
