### ISSUE TITLE
Project 1 Share Thread

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e2-fall22#23]
Hi everyone,

In this thread, I'd like you all to check out each other's Project 1s as an opportunity to explore outside code.

To kick things off, below are a few excellent projects to pick from:

+ War Card game by Richie C.: [Github Code](https://github.com/richiecarey/e2/tree/main/p1) | [Project URL](http://e2p1.richiecarey.com/)
+ Blackjack by Bradley R.: [Github Code](https://github.com/bar181/e2/tree/main/p1) | [Project URL](http://e2p1.bradross.me/)
+ Chess by Robert H: [Github Code](https://github.com/RobertHolzhauser/e2/tree/main/p1) | [Project URL](http://e2p1.robertholzhauser.me/)

Check out the app and then look through the code and make notes on any of the following:
+ Are there any parts of the code that you found interesting or taught you something new? 
+ Do you have any notes for improvement?
+ Are there any parts of the code that you don't understand? 
+ Are there any built in PHP methods that were used that you hadn't yet encountered? Explain what the method is and what it does.
+ Anything else that sticks out to you...

**Reply to this thread with your notes, and also include a link to your project on your server and in Github.**

**When coming to this thread, pick a project that has not already been responded to, pulling from the replies that come in.**

**Comment by anc6314** [comment]
Looking at [Richie Carey's war simulator](https://github.com/richiecarey/e2/tree/main/p1) because that is the one that I did as well.  Looking at his code, I learned about the tailwindcss library which is very cool and was new to me.  I also liked the way he used it to color code the cards in the view.

The code overall looks great but on the design side, I personally wouldn't have made $outcome an array.  We aren't searching for it so not sure that part is useful.  I don't like in line string literal / constants (aka magic strings) either though.

Anyway, here are my project details:
War card game by Anthony Coleman: [Github](https://github.com/anc6314/e2/tree/main/p1) | [Project](http://e2p1.anthonycoleman.me/)

**Comment by bar181** [comment]
@Richie The way you added color styling rocks
@Anthony  and @Richie: I didn't know you could have array keys with spaces.  I did find the spaces in the keys took a little while for me to understand (not bad just different). Both game play logics make sense and the code is easy to follow
@Robert : I hope you continue this project, I would like to play a person v computer version

Interesting how three of us used very different approaches to create a deck of cards. I'm working on a function to create a deck for question 3 this week

**Comment by RobertHolzhauser** [comment]
Richie - I hadn't heard of the Tailwinds framework before, it looks pretty cool!  I'm gonna check it out more.  

Regarding the View:
I like that you made the title dynamic with a php block, I hadn't ever thought to do that.   I also really like how you made a php block for the class that defines the players styles.  And it was brilliant to make that an associative array.  Nice way to populate the table, with php blocks for every cell.  

Regarding the Controller:
Very clever use of the array of suits and array of ranks to hold the deck of cards.
I didn't know you could use the kind of structure like `while (($player1 and $player2) ` to check if arrays were empty or not,
  and as a condition for a loop.  Really nice!!

All the best,
Robert

**Comment by richiecarey** [comment]
@anc6314 @RobertHolzhauser .. your War and Chess projects are excellent .. @bar181 well done, excellent BlackJack implementation .. comments are clear and helped walk me through your code, super helpful. the `$gameRules` and `$aiLogic` arrays are very clever .. I had considered BlackJack briefly but was unsure about the hit / stand logic so the`$standDecision` approach clicked for me .. nice job everyone!

**Comment by q8** [comment]
I took a look at the War Card game and what caught my eye was the double foreach loops inside each other. I didn't know it was possible. I'm not sure how I would use that in my project but it was super interesting and creative.

My Project 2 links:
[Project](http://e2p2.qa.bi/) | [Github](https://github.com/q8/e2/tree/main/p2)

**Comment by ghost** [comment]
Cards Game:
I see that array key are included as symbols, any idea how to do it? is font awesome one of the possibilities?

**Comment by richiecarey** [comment]
Hi @2015cambridge ...

For my project I used the standard Unicode characters ...

[https://en.wikipedia.org/wiki/Playing_cards_in_Unicode](https://en.wikipedia.org/wiki/Playing_cards_in_Unicodel)

.. I was able to copy and paste those characters right from that page just as you would any other string of text.

Hope this helps!

Richie

[Github Code](https://github.com/richiecarey/e2/tree/main/p1) | [Project URL](http://e2p1.richiecarey.com/)

**Comment by shawnnasseri** [comment]
got to play with the rand function and sessions.

**Comment by andlearnmore** [comment]
Richie - I like the way you used php to dynamically populate the title--I hadn't thought to do that. I learned a lot from your code in terms of how to create a deck and apply the styling--which looked so good in your project! One question I had with how you dealt the cards is what would happen if your deck had an odd number of cards and so the while-loop could only execute the first part of that loop?

Bradley - Your planning was really thoughtful; I appreciated reading your ReadMe file and seeing how you thought through the process.

Robert - From your code, I learned how to determine which player's turn it is in a 2-player game. Thanks!

Anne 
[Github Code](https://github.com/andlearnmore/e2/tree/main/p1) | [Project URL](http://e2p1.andlearn.me/)

**Comment by traveler9878** [comment]
I don't see any projects available yet that haven't been commented on...

Follow up:  I did find that folks had commented on the chess, war, and blackjack and then put links to their own projects at the end but it wasn't entirely clear to me at first that the links were for their projects because they didn't include the project names...  I'm adding my project name below for anyone who might want to comment on mine...

I made my comments on the Rainbow card game below which I thought was very well organized.  My project links are below.

Thanks.

DICE by David Curtis:

[link to p1](http://e2p1.davidcurtis.me/index.php)

Here is the link to my github repo for p1: [github for p1](https://github.com/traveler9878/e2/tree/main/p1)

**Comment by traveler9878** [comment]
This is a reply to the Rainbow Card Game above...  

Are there any parts of the code that you found interesting or taught you something new?  I found it to be very clean and well organized in general.

Do you have any notes for improvement?  I think there are opportunities to introduce some objects and methods going forward around the deck and the results

Are there any parts of the code that you don't understand? no

Are there any built in PHP methods that were used that you hadn't yet encountered? Explain what the method is and what it does.  Didn't notice any

Anything else that sticks out to you...:  very clean and well organized with regard to separation of concerns

**Comment by berhanwa** [comment]
Hi @traveler9878, great job on your dice game for project one! I think your code is well-arranged and straightforward.

One thing that could help streamline things further could be implementing ternary operators in your if constructs. 

Links to my first project: [Game URL](http://e2p1.bethlehemhes.me/) & [Github Code](https://github.com/berhanwa/e2/tree/main/p1)

**Comment by kgondim** [comment]
### Hi @raveler9878:
### I also built a dice game, so I wanted to take a look at this one. The fundamentals are very similar, though you did a nice job including more logic to make a very simple game much more interesting. I'm not sure I completely understand how to play by the instructions, but it makes much more sense once I've looked at the code. The logic looks solid, and I sure about any potential refactoring. 


### Link to my project 1 dice game : <http://e2p1.vestige-kg.me>
### Github: <https://github.com/kgondim/e2/tree/main/p1>

**Comment by richiecarey** [comment]
Hi @andlearnmore ..

> what would happen if your deck had an odd number of cards and so the while-loop could only execute the first part of that loop?

Good question! It looks like `$player2[] = array_shift($deck)` would add a null value to the `$player2[] array` so Player 2 would have 26 cards but one card would be null. The while loop would complete as expected but that null value would come back and cause problems later on in the program.

I guess this is okay for this specific implementation as the game always uses an even number of cards and deals to two players but it's true this could be more generic.

**Comment by duyvhh** [comment]
The Blackjack game by Bradley is very written. I like that the code is documented and sectioned in a way that is very easy to follow and maintain.  The use of Unicode characters to represent all the shapes are excellent. Double while loops in the code is usually prone to infinite loop, however, Bradley handled it very well here

Links to my first project: [Rock Paper Scissors](https://github.com/bar181/e2/tree/main/p1)
It is private, please ping me and I'll add you as contributors
