### ISSUE TITLE
fullName exercise error

### ISSUE THREAD

**Issue by ghost** [susanBuck/e2-fall22#25]
Hi all,

I get an error on line 27.  I would appreciate any help.

Gitbub code:
https://github.com/2015cambridge/e2/blob/b1653d81e12598f3cf939613d09cc388ed4a0eb3/practice/Classes/Person.php

Server:
http://e2practice.mourad-corner.com/Classes

**Comment by susanBuck** [comment]
Hi @2015cambridge -

This is the line in question:

```php
return $this->Person [$firstName].[$lastName];
``` 

You have the right idea here - you're attempting to return the firstName and lastName property of the Person class. However, the syntax is a bit off.

It should look like this:

```php
return $this->firstName." ".$this->lastName;
```

If you have questions about this, let me know.

**Comment by ghost** [comment]
Thank you for replying,

I still get this error:
`
Warning: Array to string conversion in /var/www/e2/practice/Classes/Person.php on line 28
string(11) "Array Array"`

I thought the conversion is done in this line:
`$this->Person= json_decode($json, true);`

**Comment by susanBuck** [comment]
When using the `$this` keyword, you can reference properties and methods of the class.
You can not/should not include the class name of Person when doing this. E.g., don't do this: `$this->Person`.

As an example, let's say you wanted to reference the _firstName_ property as shown in the example above... You would simply write `$this->firstName`, not `$this->Person->firstName`.

That aside, looking at this specific error - it looks like you still have code from the Catalog class (`json_decode($json)`) which would not apply in this class and should be removed.

**Comment by ghost** [comment]
Thank you
