### ISSUE TITLE
Fun way of thinking about Classes

### ISSUE THREAD

**Issue by andlearnmore** [susanBuck/e2-fall22#27]
I found this article that discusses OOP in the context of some familiar games: [Quick Tip: Intro to Object-Oriented Programming for Game Development](https://gamedevelopment.tutsplus.com/tutorials/quick-tip-intro-to-object-oriented-programming-for-game-development--gamedev-1805). I found it useful as I was working to getting my head around it all so I thought I'd share. I'd love to hear if others find it helpful/fun too.

**Comment by RobertHolzhauser** [comment]
That's a really fun article, thanks for posting it!

Got me to thinking about other games.

**Space Invaders**
Objects  -- Flyings Saucers, bullets (or whatever they shoot), Shelters, and the main defense gun.
Properties -- They would all have a position, direction of movement, velocity.
Methods -- Move, Shoot, .....

**Pong**
Objects --- Paddles, Ball.

Both would have properties of Position, Speed, Direction.
Methods of Move, Impact.

All the best,
Robert

**Comment by susanBuck** [comment]
Thanks for sharing this resource, @andlearnmore. Think I'll incorporate this into "outside readings" for future semesters!

**Comment by traveler9878** [comment]
I've never seen object oriented programming explained in terms of 80s video games... cool thanks.
