### ISSUE TITLE
Any PHP Sandbox?

### ISSUE THREAD

**Issue by ghost** [susanBuck/e2-fall22#29]
Hi everyone

I was unable to connect my second PC to the server for some reason.
Is there a website where you can code in PHP like JSFiddle or Codepen?
I want numerous files in a single folder (like the ones we are building for project one  or two)

Thank you

**Comment by susanBuck** [comment]
https://codesandbox.io offers PHP sandboxes. It's not something I've used extensively - just a quick test now - so I make no guarantees how good it is. : )

**Comment by ghost** [comment]
Thank you very much
