### ISSUE TITLE
Blank page after creating the symbolic link - unknown directive "//" in /etc/nginx/sites-enabled/hes

### ISSUE THREAD

**Issue by ghost** [susanBuck/e2-fall22#3]
Hi everyone,

Everything worked perfect, except when I created the link :
```bash
> ln -s /etc/nginx/sites-available/hes /etc/nginx/sites-enabled
```

I would appreciate it if anyone can help me to figure out the issue. (see screenshots below)

Thanks

![1](https://user-images.githubusercontent.com/99295470/189158712-f4d37594-50dc-4ec8-8e26-a328b6ec6f38.png)

![2](https://user-images.githubusercontent.com/99295470/189158749-ac3a8f91-dbb9-4150-a783-7c8b358b5dcf.png)

![3](https://user-images.githubusercontent.com/99295470/189158757-e363e0c1-51ff-458a-b3c6-b48083acbcd5.png)

**Comment by susanBuck** [comment]
Hi @2015cambridge -

Apologies - this is my mistake. I added comments in the config in the notes to help clarify things, forgetting that you can't use `//` for comments in nginx config files.

Remove any of the lines starting with `//` and try again. I have updated the notes with this fix.

**Comment by susanBuck** [comment]
Just to clarify, this is what it should look like (swap `hesweb.xyz` with your domain):

```
server {
    listen 80;
    server_name e2practice.hesweb.xyz;
    root /var/www/e2/practice/;

    index index.php index.html;

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.0-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
```

**Comment by ghost** [comment]
Thank you so much for the quick reply.
