### ISSUE TITLE
Checkboxes array

### ISSUE THREAD

**Issue by ghost** [susanBuck/e2-fall22#31]
Hi,

I'm using multiple choice as checkboxes, but the "var_dump" array is printing only the last checkbox and not all of them.

I don;'t know what i'm doing wrong, and I will appreciate any help.

Link  to the code:

[https://github.com/2015cambridge/e2/tree/main/p2](url)

**Comment by ghost** [comment]
Solved, it has to be  `name= 'choice[]'` instead of just `name='choice'`

**Comment by susanBuck** [comment]
Glad you got this sorted out, @2015cambridge.

For future reference/anyone else facing this same question, more details here: 
https://hesweb.dev/e2/notes/php/form-inputs-misc#checkbox-groups
