### ISSUE TITLE
Undefined key

### ISSUE THREAD

**Issue by ghost** [susanBuck/e2-fall22#32]
Hi,

When I return the array of choices, it does give me only the checked values
I want to check if a checkbox is not checked.

this is my code and I'm sure the last condition should be different:

**```
if ($choice[0]=='choice1' && $choice[1] == 'choice2'   &&  $choice[2] == ' '  ) {
    $result= '$my_result';
}
```**

**Comment by RobertHolzhauser** [comment]
You may need to check for null.  I think there's a function that will tell you if either choice is null.

**Comment by ghost** [comment]
Thank you very much
