### ISSUE TITLE
Having trouble translating game logic into OOP

### ISSUE THREAD

**Issue by berhanwa** [susanBuck/e2-fall22#33]
Hey there, I am working on a game of rock paper scissors. For this project, I realize we need to apply the principle of Do not Repeat Yourself, so I have been trying to work out how to refine my code but I'm not sure if I'm missing a step or two. This is what I have in my process.php file:

```php
<?php

        $draw = $_POST['draw'];

        $moves = ['rock', 'paper', 'scissor'];
        $userDraw = $draw;
        $computerDraw = $moves[rand(0, 2)];
        $winner = '';
        
        function decideWinner() {
            if ($userDraw == $computerDraw) {
                return 'It was a tie';
            } elseif ($userDraw == 'rock') {
               return $computerDraw == 'paper' ? 'Computer wins' : 'User wins';
            } elseif ($userDraw == 'paper') {
                return $computerDraw == 'scissor' ? 'Computer wins' : 'User wins';
            } elseif ($userDraw == 'scissor') {
                return $computerDraw == 'rock' ? 'Computer wins' : 'User wins';
            }
        }
```

**Comment by andlearnmore** [comment]
Will you be using $moves again? If not, maybe you don't need to define that array separately.

**Comment by RobertHolzhauser** [comment]
If you want to move it into OOP, one thing you could do is to make a Game class holding the draws for computer, user and winner for that game.  Then you could then further extend that and also make a GameS class which would have an array of games to hold history (array of game objects as a property), and perhaps even a method to tally up the winner overall so far.    

Robert

**Comment by susanBuck** [comment]
Hi @berhanwa -

Good to see students thinking about DRY (Don't Repeat Yourself) code. Keep in mind, though, that given the relatively simple nature of these games, you might not actually encounter a situation where your code is repeating itself. Given this, it's very possible you can complete the project without needing to apply OOP, functions, or any other code organization techniques we've looked at.

(I spoke to this a bit in the [Week 8 Part 3 video](https://www.youtube.com/embed/HTxWS5yclRo?rel=0&showinfo=0) between the 2:35-3:18 mark.)

That being said, you can choose to apply these concepts just for the sake of practice. @RobertHolzhauser laid out a good plan for this in terms of organizing all of the game functionality into a Game class. Once you do this, all of the Rock Paper Scissors specific tasks will be outsourced to that class and the process controller will be just responsible for handling the form data, interfacing with the Game class to get the results, and redirecting the user with the results. This approach is something you will see in bigger scale projects where the role of the controller is almost to act as a "traffic cop", handling incoming data, sending it to be processed, then passing on the results. 

Per our email exchange, we'll be connecting today or tomorrow via Zoom to talk more about this question so I won't go into too much more detail right now. I will follow-up more with this post after that though, for other students who might be curious about this.

**Comment by traveler9878** [comment]
I like the idea of keeping a list of wins/losses, I did a dice game and built in a bet amount but opted to hold off on adding running totals until we get to adding database into the work.
