### ISSUE TITLE
autoload can resolve namespace

### ISSUE THREAD

**Issue by traveler9878** [susanBuck/e2-fall22#35]
I'm walking through the composer setup and I have copied the game code into index.php and the Game object can't be resolved.

**Comment by susanBuck** [comment]
Can you update your e2 repository with the latest code? It's hard to say what is going on without seeing more context.

**Comment by traveler9878** [comment]
Composer installed, I have the vendor folder in my project, and the rps game code is downloaded.  The one thing that was strange following the composer setup instructions is that i did not get prompted to overwrite the php.ini.  Calling it a day will revisit.  Thanks.

**Comment by traveler9878** [comment]
hi, sure, one sec

**Comment by traveler9878** [comment]
it's uploaded to git

**Comment by traveler9878** [comment]
The only thing I see is that the src directory isn't included in the require path but it's late so I'm thinking some sleep is needed to revisit...

**Comment by susanBuck** [comment]
When I visit http://e2rps.davidcurtis.me I see a blank white screen.

This makes sense because if we look at [rps/index.php](https://github.com/traveler9878/e2/blob/main/rps/index.php) there's no output being produced.

Try wrapping `$game->play('rock');` in a `var_dump` so results are output to the page:

```php
var_dump($game->play('rock'));
```

**Comment by traveler9878** [comment]
I'm getting the red line under Game() with an undefined error message on mouseover, i'll wrap the call to play though and update the repository

**Comment by traveler9878** [comment]
lol those are the hardest problems to solve the ones where there's no problem and it's working... intellisense issue

**Comment by susanBuck** [comment]
:-) 

Yah seems like a VSCode/intellisense issue - I'd suggest closing and re-opening the index.php file. It's possible it just isn't registering the latest composer autoload config.

**Comment by traveler9878** [comment]
I worked on the game assignments and came back to it and it's working now...

**Comment by traveler9878** [comment]
No red line under Game()

**Comment by traveler9878** [comment]
Thanks!
