### ISSUE TITLE
Walking through this weeks code including About page

### ISSUE THREAD

**Issue by traveler9878** [susanBuck/e2-fall22#37]
No issues getting through this weeks materials, just posting here to start a thread in case anyone has issues they want to talk about regarding the About page.  I did manage to generate a couple of errors which provided the guidance necessary to find the updates required.  If anyone has issues with errors on the about page I suggest you post before spending lot's of time struggling, it may be something simple in the syntax.

**Comment by traveler9878** [comment]
Since this threat is still open, I'll say I'm getting a crash on trying to access the products view on this weeks code.

**Comment by traveler9878** [comment]
Here's the error, calling it a night though:
```php
Fatal error: Uncaught BadMethodCallException: Method Illuminate\View\Factory::view does not exist. in /var/www/e2/zipfoods/vendor/illuminate/macroable/Traits/Macroable.php:113 Stack trace: #0 [internal function]: Illuminate\View\Factory->__call() #1 /var/www/e2/zipfoods/vendor/jenssegers/blade/src/Blade.php(111): call_user_func_array() #2 /var/www/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(244): Jenssegers\Blade\Blade->__call() #3 /var/www/e2/zipfoods/public/index.php(15): E2\App->route() #4 {main} thrown in /var/www/e2/zipfoods/vendor/illuminate/macroable/Traits/Macroable.php on line 113
```

**Comment by susanBuck** [comment]
@traveler9878 - Can you run `composer update` within your zipfoods directory? This could be a bug in the framework that was fixed in recent versions. If it's still not working after doing that, let me know.

**Comment by traveler9878** [comment]
that fixed it, on the first page reload after the composer update i got a 404 but on the second reload it worked

**Comment by traveler9878** [comment]
Thanks!

**Comment by susanBuck** [comment]
Glad it's resolved! : ) Going to close this thread but feel free to re-open or start a new thread if you run into any other hiccups.
