### ISSUE TITLE
Issue with git push!

### ISSUE THREAD

**Issue by racheleverett** [susanBuck/e2-fall22#40]
Another issue I have for last couple of days is that I can not push my commits, when I press commit and push it just shows an endless loading animation.

I have gone through the lesson, deleted and installed the key on git, ran `ssh -T git@github.com` which returned `Hi racheleverett! You've successfully authenticated, but GitHub does not provide shell access.` as expected.

`git config --list` command returns the following
![image](https://user-images.githubusercontent.com/40373952/201521902-4a221ac9-3106-43ce-b506-9d6d93295524.png)

But still it's not working. Please help.

**Comment by susanBuck** [comment]
Hi @racheleverett -

I just logged into your server to take a look. I was able to commit/push all your pending commits without issue, so I don't think it's an issue with your server/git configs.

Now that I've got everything in sync, can you try making a change and going through the process to sync with Github (stage/add, commit, push) to see if it's giving you the same issue?

**Comment by racheleverett** [comment]
I just committed product updates, it seems to be working now. Thank you.

**Comment by susanBuck** [comment]
Excellent. If it happens again, let me know.
