### ISSUE TITLE
Error when using Faker in seedReviews

### ISSUE THREAD

**Issue by bar181** [susanBuck/e2-fall22#44]
file: AppCommand.php
function: seedReviews():
line:  $faker = Factory::create(); (Factory is underlined as an error)
error: Undefined type 'Faker\Factory'.intelephense(1009)

I checked stackoverflow and found a work around by changing the settings for intelephense but don't like it. 
Specifically response #7 in the approved answer worked by disabling 2 checks in intellephense.  I don't see the error anymore but assume this setting change can impact other stuff.

https://stackoverflow.com/questions/59149877/visual-studio-code-php-intelephense-keep-showing-not-necessary-error

**Comment by bar181** [comment]
Forgot to add context.
Yes this error occurs after adding: use Faker\Factory;
And yes, the seeding data works as expected.  It looks like just a syntax message when using VSCode

**Comment by susanBuck** [comment]
Hi @bar181 -

I connected to your server to try and recreate but I'm not seeing any errors/underlines on my end:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/237711/204065723-419b38a3-3d81-4828-8056-7e889ff89423.png">

Can you try restarting VSCode - it's possible it's just not yet recognizing the addition of the Faker package.

If that doesn't do the trick, let me know.

**Comment by bar181** [comment]
It worked !
Off and On again worked.  
I reset the intelephense back to normal settings and all looks okay after restarting VSCode. 
Thank you !

**Comment by susanBuck** [comment]
no prob, glad it worked!

**Comment by richiecarey** [comment]
I too had the same issue and restarting VSCode resolved the issue here as well .. thanks!
