### ISSUE TITLE
Remote Debug??

### ISSUE THREAD

**Issue by traveler9878** [susanBuck/e2-fall22#45]
I have my new form working and my list reviews but when I work on it to get it the way i want it I've found it problematic that I don't have the debugger setup.  I'm trying to set it up now.  Will post here as it goes....  Adding this to the php.ini now:
zend_extension=xdebug.so
xdebug.remote_enable=1
xdebug.remote_host=192.168.100.9
xdebug.remote_port=9000

since vscode is running on the server i'm going to change the IP to 127.0.0.1

**Comment by susanBuck** [comment]
Hi @traveler9878 - Checking in to see how thing went. Were you able to get xdebug up and running? Let me know if you need any assistance.

**Comment by traveler9878** [comment]
I was able to update the ini file updated but had to stop working on it due to Thanksgiving.  Most of the documentation online about how to set it up seems to be specific to setting it up with Apache.
