### ISSUE TITLE
Usage of sessions in P3?

### ISSUE THREAD

**Issue by kevinzomg** [susanBuck/e2-fall22#48]
Hi, I'm wondering if the intent of the final project is to fully utilize databases in place of sessions? Or would we be allowed to continue using sessions while writing other data to a database? For example, my P2 used sessions to keep track of moves in a game. I am considering using a database to keep track of the player's score after each game. Unsure if I'm wording my question correctly.

**Comment by susanBuck** [comment]
Hi @kevinzomg - You can still use sessions in Project 3. I think your example of using sessions to track moves and the database to track score of each game is a good plan.
