### ISSUE TITLE
Issue outputting either the value from the session or from database to the view

### ISSUE THREAD

**Issue by kgondim** [susanBuck/e2-fall22#49]
Hi @susanBuck,

I've been spinning my wheels outputting a value from a session from a form to the view, and alternatively that same value that is inputted into the database. 

I'm modeling some of the code in my controller after the zipfoods example, in that I'm trying to use the same method as here:
` $productSaved = $this->app->old('productSaved');`

to capture the session value and render to the page, but it seems to be a boolean or something because the output is "1"

I also tried to retrieve the value with:

`$variable = $this->app->input();`
but not sure how to indicate I want to get the instant or most recent value
 
I also tried 

`$variable = $this->app->sessionGet();`

Each of these, when I try to render `{{ $variable }}` or 
`{{ $variable['variable'] }}` in the blade template, it is null or I get an error that it is undefined.

I also tried methods to retrieve the value from the database, but I'm not really sure again, how to indicate I want to get the instant or most recent value.

My last commit for p3 to Github is "game edits"

Any guidance would be greatly appreciated!

**Comment by acoleman-apc** [comment]
Not sure how much help I'll be but I'll try.  In my code I use something like this in the view:
`<form method='POST' action='/play/process'>
                            <tr>
                                <td>
                                    <input type='radio' id='keep' name='choice' value='keep' checked>
                                    <label for='keep' class="black">Keep</label>
                                </td>
                                <td>
                                    <input type='radio' id='shuffle' name='choice' value='random'>
                                    <label for='shuffle' class="black">Get random card</label>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <button class="btn btn-success" type='submit'>Play</button>
                                </td>
                        </form>`

And then this in the controller:
`$choice = $this->app->input('choice', '');`

Hope this helps!

**Comment by anc6314** [comment]
Not sure how much help I'll be but I'll try. In my code I use something like this in the view:
<input type='radio' id='shuffle' name='choice' value='random'>

And then this in the controller:
$choice = $this->app->input('choice', '');

Hope this helps!

**Comment by susanBuck** [comment]
FYI Taking a look at your code now and will reply again shortly.

**Comment by susanBuck** [comment]
Hi @kgondim -

To help answer your question, I'd like to first better understand your goals, especially as it relates to the two tables you have (`guesses` and `results`).

It seems from your design that a user only gets 1 guess before a winner is determined. Based on this, I'm wondering if the `guesses` table is necessary. What if the `results` table just has a `guess` field that tracks the guess for each iteration of the game?

Let me know if this sounds like what you're envisioning, and if it is, I can give further advice on the use of sessions vs. database, output, etc.

If it's not what you were envisioning, let me know what you were looking to see and we can also go from there. : )

**Comment by kgondim** [comment]
@anc6314 thanks--I did try that with the name from the input element as the argument. (even though not reflected above), but maybe I'm missing the empty string as the second argument?

@susanBuck thanks! Just mentioning that I mentioned my last commit above, but that commit is not relevant.

**Comment by kgondim** [comment]
@susanBuck my goal was to try to either retrieve `guesses` from the session or store/retrieve from database, so I could output to the round history page if I wanted. 

You're correct in the way I have it set up to start. I just wanted to get the different moving parts working first at a basic level, and then build out from there. I was going to add more guesses for each round for which there would be a winner, and add more rounds. Basically, I was thinking to tally each `win` into a cumulative score.

I guess I was thinking that having a separate table to store `guess` data would make it easier to track each guess. If I structured the game to have multiple guesses for each round, then I'm not sure how I could distinguish the `guesses` from one another.

Let me know if you need me to clarify further, and thanks so much!

**Comment by susanBuck** [comment]
Ok, that makes sense that you're working on a simple iteration first. Good approach!

In the spirit of that, I suggest removing the code to record guesses to begin with. It just makes things more complicated right now because not only do you need to record the guess, you need to record what "round" or "game" that guess is associated with.

Instead, focus on the `games` table, where each submission of the form is a single game that gets recorded.

Building on that, I have some suggestions for code reorganization for you. Right now, I see two "processing" steps that need to happen when the form is submitted:

+ First, you have to determine if they're a winner and 
+ Second, you have to record the results to the database.

However, these two processing steps are spread out over two methods (`game` and `save`). I think it would be more logical if both these processing steps happened in `save`. You might even rename the `save` method to something more generic like `process`.

That way the `game` method is not responsible for any processing, only showing the form and results.

To demonstrate the above tips, here's some code to study:

```php
/**
 * Show the game form (and results if they exist)
 */
public function game()
{
    # If we’re redirected here from the process method
    # there will be data flashed to the session we can retrieve
    # and pass to the view
    $guessSaved = $this->app->old('guessSaved');
    $winner = $this->app->old('winner');
    $playerTotal = $this->app->old('playerTotal');
    $guess = $this->app->old('guess');
    
    return $this->app->view('game', [
        'guessSaved' => $guessSaved,
        'winner' => $winner,
        'playerTotal' => $playerTotal,
        'guess' => $guess,
    ]);
}

/**
 * Process the game form
 */
public function process()
{
    $this->app->validate([
        'guess' => 'required'
    ]);

    # Get the player’s guess from the form data
    $guess = $this->app->input('guess');

    # Game logic
    $dice = [1, 2, 3, 4, 5, 6];
    $playerTotal = $dice[rand(0, 5)] + $dice[rand(0, 5)];
    
    # Determine if they're a winner
    # Record as 1 (winner) or 0 (not a winner) since
    # the `win` field in the `results` table is expecting an integer
    $winner = $guess == $playerTotal ? 1 : 0;
    
    # Write results to database
    $this->app->db()->insert('results', [
        'win' => $winner,
    ]);
    
    # Redirect back to the game page with the results
    $this->app->redirect('/game', [
        'guessSaved' => true,
        'winner' => $winner,
        'playerTotal' => $playerTotal,
        'guess' => $guess,
    ]);
}
```

**game.blade.php:**
```html
@section('content')
    <h2>About</h2>
    <p>Play the game</p>

    {{-- FORM TO PLAY THE GAME --}}
    <form method='POST' id='new-guess-form' action='/process'>
        <h3>Guess</h3>

        <div class='form-group'>
            <label for='guess'>Guess (number 2-12)</label>
            <input type='number' class='form-control' name='guess' id='guess' min='2' max='12' required
                maxlength='2' size='10' value='{{ $app->old('guess') }}'>
        </div>

        <button type='submit' class='btn btn-primary'>Submit guess</button>
    </form>

    {{-- OUTPUT RESULTS --}}
    @if ($guessSaved)
        <div class='alert alert-success'>
            <p>Thank you, your guess was entered!</p>
            <p>The roll was {{ $playerTotal }}.</p>
            <p>You guessed {{ $guess }}.</p>

            @if ($winner)
                <div>You won!</div>
            @else
                <div>You lost, please try again!</div>
            @endif
        </div>
    @endif

    {{-- OUTPUT ERRORS --}}
    @if ($app->errorsExist())
        <ul class='error alert alert-danger'>
            @foreach ($app->errors() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    @endif

@endsection
```

Here's a demo of the above code: http://kgondim-p3.hesweb.xyz/game

Building on this, your next step would be to have a page that displays the results that are being saved to the `games` table (similar to the [game history page in the P3 example](https://e2p3.hesweb.dev/history)).

Once you get that working, you have the key components needed to meet the project requirements. And then - time permitting - you could work on evolving it so you had multiple rounds/guesses.

Let me know if you have any questions about any of the above code/suggestions!

**Comment by kgondim** [comment]
Thank you so much @susanBuck,

This makes perfect sense. It seems as though I was close with the actual code but didn't understand the order of steps needed for processing the data. This has been the challenge for me!

**Comment by susanBuck** [comment]
Glad it made sense! Going to close this thread but feel free to re-open or start a new thread if there are any other questions.
