### ISSUE TITLE
Issue setting up migrations in p3

### ISSUE THREAD

**Issue by berhanwa** [susanBuck/e2-fall22#52]
Hi, I created the migrate method in my AppCommand.php file and included the createTable code. When I tried testing in terminal by invoking console and the migrate method, I got the PHP Fatal error message shown in the screenshot. 

Has anyone run into something similar, and possibly have a solve for it? 

<img width="987" alt="Screenshot 2022-12-09 at 1 25 04 AM" src="https://user-images.githubusercontent.com/70812449/206647786-9301487e-3a50-40d9-a105-46745af2949b.png">

**Comment by susanBuck** [comment]
Hi @berhanwa - Based on the output of "Access denied for user `root`" it looks like your .env file may still have to database connecting as the default root user. You should update this to reflect the `hes` MySQL user we created. Be sure to update the password as well.


For reference, here are the notes on when we created the new user:
https://hesweb.dev/e2/notes/php/db-setup#create-a-new-mysql-user

And here are the notes on updating the .env:
https://hesweb.dev/e2/notes/php/e2framework/database#database

**Comment by berhanwa** [comment]
That was it 😅 thank you so much @susanBuck!

**Comment by susanBuck** [comment]
You're welcome! : )
