### ISSUE TITLE
question about seed

### ISSUE THREAD

**Issue by JacquiLJQ** [susanBuck/e2-fall22#54]
When seeding, must the dummy data comply with the game logic?  For example, can I have something looks like this:
<img width="672" alt="截屏2022-12-09 下午8 24 28" src="https://user-images.githubusercontent.com/104879321/206701927-bb8a71de-a9a4-43bf-bdcf-b2eea0e65ac5.png">
That will cause a situation where both tie and win are true. Is this allowed in seeding?

**Comment by richiecarey** [comment]
I was wondering that too ... in the end I chose to hard code some 'real' game data so the seeded games would display correctly.

**Comment by susanBuck** [comment]
Yes, the data should comply with the game logic. You want it to most accurately represent the kind of real data you will be working with.

**Comment by JacquiLJQ** [comment]
@susanBuck Got it. So can I use hard-coded data to make it comply with the game logic?

**Comment by susanBuck** [comment]
Hi @JacquiFreeElectron - Absolutely. Generating random seed data can be useful for efficiency, especially if you want to seed a non-trivial amount of data. But there's nothing to say you can't hard-code your data.

**Comment by JacquiLJQ** [comment]
@susanBuck Got it. Thank you so much!
