### ISSUE TITLE
"Suite acceptance was not loaded"

### ISSUE THREAD

**Issue by traveler9878** [susanBuck/e2-fall22#55]
Cont sure what is going on with my codeception but when I try to generate the cest for P3 I am getting an error about "acceptance was not loaded".  Googling it now...

**Comment by susanBuck** [comment]
@traveler9878 Try what I noted I did in this thread: https://github.com/susanBuck/e2-fall22/issues/50

If that doesn't fix it, let me know and I can log into your server and take a look.

**Comment by traveler9878** [comment]
i deleted the tests directory and the codeception.yml and ran bootstrap again, same problem.

**Comment by susanBuck** [comment]
Ok thanks for trying that. Going to log into your server now and take a look. Will report back shortly.

**Comment by susanBuck** [comment]
I was able to generate a cest in your P3 on your server:"

```xml
root@hes:/var/www/e2/p3# php vendor/bin/codecept generate:cest Acceptance Example
Test was created in /var/www/e2/p3/tests/Acceptance/ExampleCest.php
```

Can you share the exact command you're running that is generating the error you're reporting (`acceptance was not loaded`)?

Also, since I had you re-install Codeception, don't forget to update `/var/www/e2/p3/tests/Acceptance.suite.yml` as described here: https://hesweb.dev/e2/notes/php/testing-codeception#setup

**Comment by traveler9878** [comment]
I just closed the terminal and started a new one and ran the following:
root@hes:/var/www# cd e2
root@hes:/var/www/e2# cd p3
root@hes:/var/www/e2/p3# php vendor/bin/codecept generate:cest acceptance P3

In Configuration.php line 338:
                                   
  Suite acceptance was not loaded  
                                   

generate:cest <suite> <class>

root@hes:/var/www/e2/p3#

**Comment by traveler9878** [comment]
I see it's an upper case A in Acceptance

**Comment by traveler9878** [comment]
It's correct in the notes, which I didn't cut and paste, and lower case in the youtube demonstration

**Comment by traveler9878** [comment]
P3Cest created

**Comment by susanBuck** [comment]
Apologies for the confusion. To help clarify, there's an elaboration in the [Week 14, Part 3](https://www.youtube.com/embed/Aq6mcZ2-IhY?rel=0&showinfo=0) video at 5:23 about this capitalization difference.

**Comment by traveler9878** [comment]
I may recall this A issue being pointed out in the past, I know we talked about someone switching case to conform to class naming conventions... yes that's it

**Comment by traveler9878** [comment]
I thought it was a really bad idea for them to do that at the time...

**Comment by traveler9878** [comment]
I was picturing the team going... "Look this works... Let's change it!"
