### ISSUE TITLE
Two connections?

### ISSUE THREAD

**Issue by ghost** [susanBuck/e2-fall22#7]
Hi,

Is it possible to connect two computer from different location and different operating system to the same digital Ocean server?

**Comment by susanBuck** [comment]
Yup! It's one of the benefits of our remote development setup.

To get a second computer to connect to your server you need to add a SSH key for that computer on the server.

To do this, [follow these instructions](https://hesweb.dev/e2/notes/infrastructure/ssh-keys#generate-ssh-key-pair-on-your-computer) for generating a key pair on the second computer. Copy the contents of the resulting .pub key.

Then, from your first computer, connect to the server and open the file `~/.ssh/authorized_keys` and add the above .pub key at the end of the file.

You should now be able to SSH connect to your server from your second key.

Note that this process is similar to when I had you add [instructor access](https://hesweb.dev/e2/notes/infrastructure/servers-config#instructor-server-access) to your server.

If you run through the above steps and have any questions, let me know.

**Comment by traveler9878** [comment]
Good question, did you get it working?

**Comment by ghost** [comment]
Thank you for replying. It doesn't seem to be working on my 2nd computer. I know that I'm doing something wrong but I can't find it. I will keep trying

**Comment by susanBuck** [comment]
If you want any help troubleshooting try running `ssh -v root@your.server.ip.address` from the computer that is failing to connect and share the output. The addition of the verbose (`-v`) flag will provide extra debugging details about why the connection is failing.

Ref: https://hesweb.dev/e2/notes/infrastructure/servers-setup#troubleshooting

In the interim, I'm going to close this thread but feel free to re-open if you continue to pursue this and want assistance.

**Comment by ghost** [comment]
after running `ssh -v root@your.server.ip.address`




![Screenshot_1](https://user-images.githubusercontent.com/99295470/192541273-54430deb-4fc6-4ee6-abf6-ac4f12808a3f.png)

**Comment by susanBuck** [comment]
From this output I see it's not trying to use the key called `hes`.

Can you confirm you [updated your SSH config](https://hesweb.dev/e2/notes/infrastructure/ssh-keys#ssh-config-file) to use that key?

Also, share the output of `ssh -v root@your.server.ip.address` from the working computer so we can compare/contrast.
