### ISSUE TITLE
PHP documentation

### ISSUE THREAD

**Issue by kgondim** [susanBuck/e2-fall22#8]
## Wondering how much of the documentation should we be internalizing

As I'm going through the readings for this week, it's not clear how far in the weeds we should be getting with each tangent on the major topic areas and subtopics. Some of it is *very* abstract, even with examples, but would probably make more sense with concrete examples for scenarios where we would use a given concept.

**Thanks!**

**Comment by susanBuck** [comment]
You don't need to go deep or understand everything right now. I'd say skim for big picture ideas and just to familiarize yourself with the information so that - when needed - you can dig deeper.

**Comment by susanBuck** [comment]
Just an update on this - I update the [Outside Readings](https://hesweb.dev/e2/readings) page with the following preface:

> To supplement/enforce the material covered this week, skim through the following documentation from php.net. It’s okay if you don’t understand 100% of the material as some of it is abstract. The idea right now is just to familiarize yourself with this documentation and broadly “preload” your brain with the information so that as we progress you can come back and dig deeper on the specific topics as needed.

Hopefully that helps clarify things better for future semesters. Thanks for raising this question - I can see how the docs would be overwhelming without a clear understanding of how much/little you're expected to absorb at this point. : )

**Comment by JenniWhitman** [comment]
I'm late to the party, but I will also add that in the "real world" docs are a constant reference. I will tell you right now I will use things then not use them for months - so I'm constantly checking back to docs for syntax, "hey, does that function also handle X", and to look for things that might be related that can help me in whatever situation I'm in. Like Susan said - don't preload, just sorta digest a bit, get a feel for what's available to you, and get comfortable traversing them so when you're in need, you have a rough idea of what's there and how to find it :)

**Comment by traveler9878** [comment]
good documentation reference is very important for a language to be successful in my opinion.  Understanding how to find it, how to interpret it, and how to apply it when needed is a critical step in any project.
