### ISSUE TITLE
Question about iterating in view code

### ISSUE THREAD

**Issue by RobertHolzhauser** [susanBuck/e2-fall22#9]
Hello,

I might be getting ahead of things a bit, because I know that our next topic will include loops.  

I noticed that in the notes and lecture for this week, under Separation of Concerns, this was an example given for view code:
``` <ul>
    <?php for($coin in $coins) { ?>
        <li><?php echo $coin; ?></li>
    <?php } ?>
</ul>
```
My question about that is it seems a little heavy or redundant on the number of php blocks declared.  Would it also work to concatenate the html, since we are still on the view page?  Something perhaps like this?
```
<ul>
    <?php for($coin in $coins) { 
        echo '<li> $coin </li>';
     } 
    ?>
</ul>
``` 

Thanks very much!
Robert

**Comment by susanBuck** [comment]
Both approaches would work, but I would lean towards the first style as it maintains the tag-like structure of HTML and better isolates the PHP and HTML. 

I do see what you mean about it seeming heavy with the opening/closing of PHP blocks, but there's no tangible performance difference.

And your instincts are correct - we will get into this very question this week. : )

**Comment by RobertHolzhauser** [comment]
Ok, thanks for the additional information.  Looking forward to this week's lecture!  :)

**Comment by susanBuck** [comment]
@RobertHolzhauser - Follow up: I just recalled that I didn't get to the discussion of loop style in views last week as promised. 

But! It will be covered in this week's (5) material. I'm going to show how to build a game with multiple results, and we'll use a loop to iterate through those results and output them.
